### ISSUE TITLE
pry-byebug and pry-stack_explorer aren't compatible

### ISSUE THREAD

**Issue by BrianHawley** [davidcelis/pry-suite#1]
According to https://github.com/deivid-rodriguez/pry-byebug/pull/6 pry-byebug and pry-stack_explorer aren't compatible. The author of pry-byebug plans to add stack exploring support through byebug, to make up for this.

You should make your suite only include pry-stack_explorer when you're including pry-debugger, at least until this incompatibility is resolved.

Nice suite though!

**Comment by davidcelis** [comment]
Fixed in 1.1.1. Thanks!
